CREATE TABLE IF NOT EXISTS notes (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL, added TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, note_id INTEGER NOT NULL,title TEXT NOT NULL, added TEXT NOT NULL ,
 modified TEXT NOT NULL, content TEXT NOT NULL, deleted INT NOT NULL, edited INT NOT NULL, FOREIGN KEY (note_id) REFERENCES notes(id),
 UNIQUE(note_id,title,edited,deleted) ON CONFLICT IGNORE);